mdapi/objects/Async_Request__c.object
<CustomObject>
    <description>Use to queue up an Asynchronous Request for processing</description>
    <label>Async Request</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Async Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Async Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Options__c</fullName>
        <description>Additional Options that can be used when processing the request</description>
        <label>Options</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Params__c</fullName>
        <label>Params</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
</CustomObject>

force-app/main/default/classes/SampleOptionsJobAsync.cls
/**
 * Sample job that does something dumb and demonstrates the use of Options field. 
 * It sets the Account.Description to the value provided in Options field.
 */
public without sharing class SampleOptionsJobAsync extends BaseAsyncHandler {

    public override String getRequestType(){
        return 'Sample Options Job';
    } 
    
    public override void execute(Async_Request__c ar)
    {
        List<Id> accountIds = ar.Params__c.split(PARAMETERS_SPLITTER);
        if(accountIds.size() == 0) return;

        Options opt = (Options) JSON.deserialize(ar.Options__c, Options.class);

        // Do something with Accounts

        List<Account> accountsToUpdate = [
            SELECT Id, Description
            FROM Account
            WHERE Id IN :accountIds
        ];

        for(Account acc : accountsToUpdate){
            acc.Description = opt.Description;
        }

        update accountsToUpdate;
    }

    public class Options {
        public String Description {get; set;}

        public Options(String description){
            this.Description = description;
        }
    }
}